In [23]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

from sklearn.neural_network import MLPRegressor

df = pd.read_csv('batsman_runs.csv')

df.sample(10)

,name,runs,balls,innings_runs,batting_position,runs_come_in,overs_come_in,match_id
6538,DR Smith,74,39,186,1,0,0.166667,1082637
15457,YBK Jaiswal,3,8,176,1,0,0.166667,1312197
5628,SE Marsh,19,15,204,4,116,11.166667,1082641
9132,DT Christian,29,19,183,3,86,10.833333,548326
6041,YV Takawale,23,7,131,8,107,18.500000,336036
6600,JP Duminy,22,15,168,5,106,14.833333,501208
8014,AT Rayudu,24,8,198,6,152,17.666667,598006
8252,MS Bisla,29,25,123,2,0,0.166667,598043
10219,SA Yadav,26,22,131,5,14,3.000000,1359523
9374,S Aravind,5,4,42,10,37,8.666667,1082617

In [24]:
# REGRESSION
x = list(zip(df.balls, df.innings_runs, df.batting_position, df.runs_come_in, df.overs_come_in))
y = df.runs.to_list()

regr = MLPRegressor(max_iter=1000)
regr.fit(x, y)

preds, actuals = [], []

for xi, yi in zip(x, y):
    preds += [max(round(regr.predict([xi])[0],1), 0)]
    actuals += [yi]

df['predicted'] = preds
df['difference'] = df.runs - df.predicted

In [25]:
# PLOT THE PREDICTED VS ACTUAL RUNS
#%matplotlib qt # uncomment to make the plot interactive in a separate window
import matplotlib.pyplot as plt
from seaborn import heatmap
from matplotlib.colors import LogNorm

freq_table = pd.crosstab(actuals, preds, colnames=['Actual'], rownames=['Predicted'])
frequency_table = freq_table.reindex(index=range(round(max(actuals))+1), columns=range(round(max(preds))+1), fill_value=0)

plt.figure(figsize=(10,10))

heatmap(frequency_table.iloc[::-1], norm=LogNorm())

plt.plot([171, 0], [0, 171], color='red')

In [29]:
# BEST INNINGS
df.sort_values('difference', ascending=False).head(10)

,name,runs,balls,innings_runs,batting_position,runs_come_in,overs_come_in,match_id,predicted,difference
6802,CH Gayle,171,65,247,1,0,0.166667,598027,116.7,54.3
2961,ST Jayasuriya,114,48,142,1,0,0.166667,336018,63.9,50.1
13325,TM Head,89,30,164,2,0,0.166667,1426295,39.6,49.4
1413,SK Raina,83,24,182,3,1,0.500000,734047,33.6,49.4
3402,AC Gilchrist,109,47,146,1,0,0.166667,335994,64.0,45.0
11450,KL Rahul,98,42,134,1,0,0.166667,1254094,53.0,45.0
2624,V Sehwag,94,41,131,2,0,0.166667,335988,49.6,44.4
2003,YK Pathan,72,22,146,4,42,7.666667,734037,29.3,42.7
16811,J Fraser-McGurk,65,18,191,3,16,1.000000,1426273,24.0,41.0
56,BB McCullum,158,73,205,2,0,0.166667,335982,117.6,40.4

In [30]:
# WORST INNINGS
df.sort_values('difference', ascending=True).head(10)

,name,runs,balls,innings_runs,batting_position,runs_come_in,overs_come_in,match_id,predicted,difference
6340,TM Dilshan,32,35,247,2,0,0.166667,598027,63.3,-31.3
6479,DR Smith,47,53,159,1,0,0.166667,598050,76.4,-29.4
6334,TM Dilshan,43,49,152,2,0,0.166667,548367,67.7,-24.7
15396,D Padikkal,41,52,134,2,0,0.166667,1254095,65.3,-24.3
378,V Kohli,27,31,199,3,40,5.000000,501244,51.1,-24.1
296,R Dravid,25,32,189,1,0,0.166667,548324,49.0,-24.0
7540,DA Warner,57,55,163,1,0,0.166667,1254080,80.4,-23.4
5555,HH Gibbs,66,58,177,1,0,0.166667,548363,89.2,-23.2
1015,ML Hayden,17,31,157,2,0,0.166667,419165,39.4,-22.4
8184,R McLaren,40,42,176,1,0,0.166667,419157,62.1,-22.1