In [69]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

from sklearn.neural_network import MLPRegressor

df = pd.read_csv('batsman_runs.csv')


df.head(10)

,runs,balls,innings_runs,batting_position,runs_come_in,overs_come_in,match_id
0,10.0,12.0,205.0,1.0,0.0,0.166667,335982.0
1,14.0,29.0,84.0,4.0,12.0,2.333333,335986.0
2,12.0,19.0,139.0,1.0,0.0,0.166667,335993.0
3,4.0,2.0,124.0,2.0,0.0,0.166667,335997.0
4,51.0,39.0,139.0,2.0,0.0,0.166667,336000.0
5,5.0,7.0,162.0,2.0,0.0,0.166667,336003.0
6,20.0,22.0,124.0,3.0,8.0,2.333333,336010.0
7,91.0,57.0,198.0,3.0,4.0,0.833333,336014.0
8,7.0,3.0,122.0,3.0,31.0,6.166667,336017.0
9,15.0,20.0,59.0,3.0,14.0,3.166667,336021.0

In [70]:
x = list(zip(df.balls, df.innings_runs, df.batting_position, df.runs_come_in, df.overs_come_in))
y = df.runs.to_list()

regr = MLPRegressor(max_iter=1000)
regr.fit(x, y)

preds, actuals = [], []

for xi, yi in zip(x, y):
    preds += [max(round(regr.predict([xi])[0],1), 0)]
    actuals += [yi]

df['predicted'] = preds
df['difference'] = df.predicted - df.runs

In [71]:
%matplotlib qt
import matplotlib.pyplot as plt
from seaborn import heatmap
from matplotlib.colors import LogNorm

# plt.scatter(actuals, preds)

# plt.ylabel("predicted")
# plt.xlabel("actual")
# plt.plot([0, 171], [0, 171], color='red')


freq_table = pd.crosstab(actuals, preds, colnames=['Actual'], rownames=['Predicted'])
frequency_table = freq_table.reindex(index=range(round(max(actuals))+1), columns=range(round(max(preds))+1), fill_value=0)

plt.figure(figsize=(10,10))

heatmap(frequency_table.iloc[::-1], norm=LogNorm())

plt.plot([171, 0], [0, 171], color='red')

In [ ]:
df.sort_values('runs', ascending=False).head(30)

,runs,balls,innings_runs,batting_position,runs_come_in,overs_come_in,match_id,predicted,difference
6802,171.0,65.0,247.0,1.0,0.0,0.166667,598027.0,118.0,-53.0
56,158.0,73.0,205.0,2.0,0.0,0.166667,335982.0,118.5,-39.5
11583,140.0,70.0,207.0,1.0,0.0,0.166667,1304112.0,116.0,-24.0
11432,132.0,69.0,195.0,1.0,0.0,0.166667,1216510.0,110.8,-21.2
5920,132.0,58.0,227.0,3.0,19.0,3.333333,829795.0,104.7,-27.3
13381,128.0,63.0,184.0,4.0,20.0,4.166667,1136602.0,101.2,-26.8
14447,128.0,59.0,218.0,2.0,0.0,0.166667,1370352.0,100.1,-27.9
7290,127.0,56.0,240.0,1.0,0.0,0.166667,419137.0,101.7,-25.3
7501,126.0,59.0,201.0,1.0,0.0,0.166667,1082627.0,97.1,-28.9
5935,125.0,51.0,240.0,3.0,18.0,4.000000,980987.0,98.2,-26.8
6794,122.0,61.0,205.0,1.0,0.0,0.166667,548372.0,101.3,-20.7
2717,122.0,57.0,215.0,1.0,0.0,0.166667,734047.0,97.3,-24.7
6997,120.0,63.0,192.0,1.0,0.0,0.166667,501206.0,101.2,-18.8
2671,119.0,55.0,169.0,2.0,0.0,0.166667,501243.0,81.6,-37.4
15468,118.0,61.0,181.0,1.0,0.0,0.166667,1359516.0,95.2,-22.8
11298,118.0,62.0,207.0,3.0,0.0,0.666667,1254061.0,102.2,-15.8
12910,118.0,63.0,200.0,1.0,0.0,0.166667,1254085.0,103.2,-14.8
3555,117.0,52.0,208.0,4.0,32.0,3.166667,335990.0,85.9,-31.1
2175,117.0,57.0,175.0,1.0,0.0,0.166667,1136620.0,87.4,-29.6
6828,116.0,56.0,214.0,1.0,0.0,0.166667,829785.0,95.4,-20.6
1016,116.0,54.0,230.0,3.0,20.0,3.000000,335983.0,98.0,-18.0
13048,116.0,61.0,195.0,3.0,0.0,0.666667,1426277.0,97.6,-18.4
12917,116.0,65.0,217.0,1.0,0.0,0.166667,1304080.0,110.6,-5.4
3949,115.0,55.0,191.0,4.0,29.0,5.333333,734049.0,91.8,-23.2
2961,114.0,48.0,142.0,1.0,0.0,0.166667,336018.0,64.8,-49.2
14961,114.0,56.0,229.0,1.0,0.0,0.166667,1175366.0,99.1,-14.9
5366,114.0,73.0,168.0,2.0,0.0,0.166667,392236.0,101.3,-12.7
7326,113.0,58.0,216.0,1.0,0.0,0.166667,548380.0,99.1,-13.9
566,113.0,72.0,172.0,1.0,0.0,0.166667,1422137.0,103.4,-9.6
5566,113.0,68.0,214.0,1.0,0.0,0.166667,336019.0,114.7,1.7